In [22]:
def load_datfile(filename):
    file = open(filename, 'r')
    text = file.read()
    file.close()
    return text
    

In [23]:
doc = load_datfile('pg1497.txt')

In [24]:
#Replace ‘–‘ with a white space so we can split words better.
#Split words based on white space.
#Remove all punctuation from words to reduce the vocabulary size (e.g. ‘What?’ becomes ‘What’).
#Remove all words that are not alphabetic to remove standalone punctuation tokens.
#Normalize all words to lowercase to reduce the vocabulary size.

import string
def clean_doc(doc):
    # replace '--' with a space ' '
    doc = doc.replace('--', ' ')
    # split into tokens by white space
    tokens = doc.split()
    # remove punctuation from each token
    table = str.maketrans('', '', string.punctuation)
    print(table)
    tokens = [w.translate(table) for w in tokens]
    # remove remaining tokens that are not alphabetic
    tokens = [word for word in tokens if word.isalpha()]
    # make lower case
    tokens = [word.lower() for word in tokens]
    return tokens

In [25]:
clean_doc(doc)

{33: None, 34: None, 35: None, 36: None, 37: None, 38: None, 39: None, 40: None, 41: None, 42: None, 43: None, 44: None, 45: None, 46: None, 47: None, 58: None, 59: None, 60: None, 61: None, 62: None, 63: None, 64: None, 91: None, 92: None, 93: None, 94: None, 95: None, 96: None, 123: None, 124: None, 125: None, 126: None}


['project',
 'gutenberg',
 'ebook',
 'of',
 'the',
 'republic',
 'by',
 'plato',
 'this',
 'ebook',
 'is',
 'for',
 'the',
 'use',
 'of',
 'anyone',
 'anywhere',
 'at',
 'no',
 'cost',
 'and',
 'with',
 'almost',
 'no',
 'restrictions',
 'whatsoever',
 'you',
 'may',
 'copy',
 'it',
 'give',
 'it',
 'away',
 'or',
 'reuse',
 'it',
 'under',
 'the',
 'terms',
 'of',
 'the',
 'project',
 'gutenberg',
 'license',
 'included',
 'with',
 'this',
 'ebook',
 'or',
 'online',
 'at',
 'wwwgutenbergorg',
 'title',
 'the',
 'republic',
 'author',
 'plato',
 'translator',
 'b',
 'jowett',
 'posting',
 'date',
 'august',
 'ebook',
 'release',
 'date',
 'october',
 'last',
 'updated',
 'june',
 'language',
 'english',
 'start',
 'of',
 'this',
 'project',
 'gutenberg',
 'ebook',
 'the',
 'republic',
 'produced',
 'by',
 'sue',
 'asscher',
 'the',
 'republic',
 'by',
 'plato',
 'translated',
 'by',
 'benjamin',
 'jowett',
 'note',
 'the',
 'republic',
 'by',
 'plato',
 'jowett',
 'etext',
 'introduct

In [26]:
tokens = clean_doc(doc)
print(tokens[:200])
print('Total Tokens: %d' % len(tokens))
print('Unique Tokens: %d' % len(set(tokens)))

{33: None, 34: None, 35: None, 36: None, 37: None, 38: None, 39: None, 40: None, 41: None, 42: None, 43: None, 44: None, 45: None, 46: None, 47: None, 58: None, 59: None, 60: None, 61: None, 62: None, 63: None, 64: None, 91: None, 92: None, 93: None, 94: None, 95: None, 96: None, 123: None, 124: None, 125: None, 126: None}
['project', 'gutenberg', 'ebook', 'of', 'the', 'republic', 'by', 'plato', 'this', 'ebook', 'is', 'for', 'the', 'use', 'of', 'anyone', 'anywhere', 'at', 'no', 'cost', 'and', 'with', 'almost', 'no', 'restrictions', 'whatsoever', 'you', 'may', 'copy', 'it', 'give', 'it', 'away', 'or', 'reuse', 'it', 'under', 'the', 'terms', 'of', 'the', 'project', 'gutenberg', 'license', 'included', 'with', 'this', 'ebook', 'or', 'online', 'at', 'wwwgutenbergorg', 'title', 'the', 'republic', 'author', 'plato', 'translator', 'b', 'jowett', 'posting', 'date', 'august', 'ebook', 'release', 'date', 'october', 'last', 'updated', 'june', 'language', 'english', 'start', 'of', 'this', 'project'

In [27]:
length = 50 + 1 # 50 input and 1 output
sequences = list()
for i in range(length, len(tokens)):
    # select sequence of tokens
    seq = tokens[i-length:i]
    # convert into a line
    line = ' '.join(seq)
    # store
    sequences.append(line)
print('Total Sequences: %d' % len(sequences))

Total Sequences: 219582


In [28]:
# save tokens to file, one dialog per line
def save_doc(lines, filename):
    data = '\n'.join(lines)
    file = open(filename, 'w')
    file.write(data)
    file.close()

In [13]:
# save sequences to file
out_filename = 'republic_sequences.txt'
save_doc(sequences, out_filename)

In [29]:
def load_doc(filename):
    # open the file as read only
    file = open(filename, 'r')
    # read all text
    text = file.read()
    # close the file
    file.close()
    return text
 
# load
in_filename = 'republic_sequences.txt'
doc = load_doc(in_filename)
lines = doc.split('\n')

In [30]:
print("Lines 10------", lines[10])
print("Lines 11 ------", lines[11])
print("Lines 12 ------", lines[12])
print("Lines 13 ------", lines[13])
print("Lines 14 ------", lines[14])

Lines 10------ is for the use of anyone anywhere at no cost and with almost no restrictions whatsoever you may copy it give it away or reuse it under the terms of the project gutenberg license included with this ebook or online at wwwgutenbergorg title the republic author plato translator b jowett posting
Lines 11 ------ for the use of anyone anywhere at no cost and with almost no restrictions whatsoever you may copy it give it away or reuse it under the terms of the project gutenberg license included with this ebook or online at wwwgutenbergorg title the republic author plato translator b jowett posting date
Lines 12 ------ the use of anyone anywhere at no cost and with almost no restrictions whatsoever you may copy it give it away or reuse it under the terms of the project gutenberg license included with this ebook or online at wwwgutenbergorg title the republic author plato translator b jowett posting date august
Lines 13 ------ use of anyone anywhere at no cost and with almost no r

In [31]:
# integer encode sequences of words
from keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer()
tokenizer.fit_on_texts(lines)
# converts all sequences from list of words to list of integars
sequences = tokenizer.texts_to_sequences(lines)

In [32]:
sequences

[[291,
  733,
  1846,
  2,
  1,
  226,
  23,
  89,
  30,
  1846,
  5,
  26,
  1,
  165,
  2,
  2833,
  2832,
  35,
  44,
  3275,
  3,
  28,
  570,
  44,
  4823,
  6581,
  21,
  37,
  1099,
  72,
  236,
  72,
  248,
  13,
  6580,
  72,
  158,
  1,
  376,
  2,
  1,
  291,
  733,
  1312,
  1392,
  28,
  30,
  1846,
  13,
  3884,
  35],
 [733,
  1846,
  2,
  1,
  226,
  23,
  89,
  30,
  1846,
  5,
  26,
  1,
  165,
  2,
  2833,
  2832,
  35,
  44,
  3275,
  3,
  28,
  570,
  44,
  4823,
  6581,
  21,
  37,
  1099,
  72,
  236,
  72,
  248,
  13,
  6580,
  72,
  158,
  1,
  376,
  2,
  1,
  291,
  733,
  1312,
  1392,
  28,
  30,
  1846,
  13,
  3884,
  35,
  3887],
 [1846,
  2,
  1,
  226,
  23,
  89,
  30,
  1846,
  5,
  26,
  1,
  165,
  2,
  2833,
  2832,
  35,
  44,
  3275,
  3,
  28,
  570,
  44,
  4823,
  6581,
  21,
  37,
  1099,
  72,
  236,
  72,
  248,
  13,
  6580,
  72,
  158,
  1,
  376,
  2,
  1,
  291,
  733,
  1312,
  1392,
  28,
  30,
  1846,
  13,
  3884,
  35,
  3887,
 

# We can access the mapping of words to integers as a dictionary 
# attribute called word_index on the Tokenizer object.
# Words are assigned values from 1 to the total number of words 
# (e.g. 7,409). The Embedding layer needs to allocate a vector representation for each word in this vocabulary from index 1 to the largest index and because indexing of arrays is zero-offset, the index of the word at the end of the vocabulary will be 7,409; that means the array must be 7,409 + 1 in length.
# Therefore, when specifying the vocabulary size to the Embedding layer, we specify it as 1 larger than the actual vocabulary.

In [33]:
vocab_size = len(tokenizer.word_index) +1

In [34]:
vocab_size

10650

In [40]:
import numpy as np
sequences = np.array(sequences)
sequences

array([[  291,   733,  1846, ...,    13,  3884,    35],
       [  733,  1846,     2, ...,  3884,    35,  3887],
       [ 1846,     2,     1, ...,    35,  3887,  2035],
       ...,
       [  287,  2249,    35, ..., 10649,     4,   320],
       [ 2249,    35,    58, ...,     4,   320,    85],
       [   35,    58,  2507, ...,   320,    85,   314]])

In [37]:
# array slicing 
X,y = sequences[:,:-1], sequences[:,-1]

In [47]:
print(X.shape)
print(X)

(219582, 50)
[[  291   733  1846 ...  1846    13  3884]
 [  733  1846     2 ...    13  3884    35]
 [ 1846     2     1 ...  3884    35  3887]
 ...
 [  287  2249    35 ...  3886 10649     4]
 [ 2249    35    58 ... 10649     4   320]
 [   35    58  2507 ...     4   320    85]]


In [38]:
y

array([  35, 3887, 2035, ...,  320,   85,  314])

In [41]:
# one hot encoding: we need to one  hot encode the output word that means converting it from an integar to vector of 0 values.
from keras.utils import to_categorical
y = to_categorical(y, num_classes=vocab_size)

In [50]:
print(y.shape)
print(y)

(219582, 10650)
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [44]:
seq_length = X.shape[1]
seq_length

50

In [55]:
# define a model
from keras.models import Sequential
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from keras.layers import Embedding
model = Sequential()
model.add(Embedding(vocab_size, 50, input_length=seq_length))
model.add(LSTM(100, return_sequences=True))
model.add(LSTM(100))
model.add(Dense(100, activation='relu'))
model.add(Dense(vocab_size, activation='softmax'))
print(model.summary())

Instructions for updating:
Colocations handled automatically by placer.
Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 50, 50)            532500    
_________________________________________________________________
lstm_1 (LSTM)                (None, 50, 100)           60400     
_________________________________________________________________
lstm_2 (LSTM)                (None, 100)               80400     
_________________________________________________________________
dense_1 (Dense)              (None, 100)               10100     
_________________________________________________________________
dense_2 (Dense)              (None, 10650)             1075650   
Total params: 1,759,050
Trainable params: 1,759,050
Non-trainable params: 0
_________________________________________________________________
None


In [57]:
# compile model
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
# fit model
model.fit(X, y, batch_size=128, epochs=4)

Epoch 1/4
219582/219582 [==============================] - 186s 849us/step - loss: 5.3783 - accuracy: 0.1635
Epoch 2/4
219582/219582 [==============================] - 184s 839us/step - loss: 5.1675 - accuracy: 0.1717
Epoch 3/4
219582/219582 [==============================] - 185s 840us/step - loss: 5.0619 - accuracy: 0.1762
Epoch 4/4
219582/219582 [==============================] - 185s 841us/step - loss: 4.9693 - accuracy: 0.1807


In [59]:
model.save('model.h5')
# save the tokenizer
from pickle import dump
dump(tokenizer, open('tokenizer.pkl', 'wb'))

In [61]:
# load model
from keras.models import load_model
model = load_model('model.h5')
# load tokenizer
# tokenizer = load(open('tokenizer.pkl'), 'rb')

In [63]:
# Generate text : prepare a seed input
# select a seed text
# select a random line of text from input text for this purpose, 
from random import randint
seed_text = lines[randint(0, len(lines))]
print(seed_text + '\n')

of brass and iron and the species will generally be preserved in the children but as all are of the same original stock a golden parent will sometimes have a silver son or a silver parent a golden son and god proclaims as a first principle to the rulers and above



In [70]:
# convert seed text to integars
from keras.preprocessing.sequence import pad_sequences
encoded = tokenizer.texts_to_sequences([seed_text])[0]
print(encoded)
# truncate sequences to a fixed length
encoded = pad_sequences([encoded], maxlen=seq_length, truncating='pre')
print(encoded)

[2, 1445, 3, 1218, 3, 1, 4746, 18, 562, 10, 1748, 6, 1, 188, 19, 17, 34, 14, 2, 1, 81, 572, 2164, 7, 1790, 849, 18, 526, 20, 7, 647, 301, 13, 7, 647, 849, 7, 1790, 301, 3, 190, 4765, 17, 7, 78, 173, 4, 1, 232, 3, 367]
[[1445    3 1218    3    1 4746   18  562   10 1748    6    1  188   19
    17   34   14    2    1   81  572 2164    7 1790  849   18  526   20
     7  647  301   13    7  647  849    7 1790  301    3  190 4765   17
     7   78  173    4    1  232    3  367]]


In [74]:
# predict proab of each word


In [77]:
# lookup the insex in tokenziers mapping with associates word
yhat = model.predict_classes(encoded, verbose=0)
out_word = ''
for word, index in tokenizer.word_index.items():
    if index == yhat:
        out_word = word
        break

In [78]:
seed_text += ' ' + out_word

In [79]:
seed_text

'of brass and iron and the species will generally be preserved in the children but as all are of the same original stock a golden parent will sometimes have a silver son or a silver parent a golden son and god proclaims as a first principle to the rulers and above the'

In [80]:
# extensions
# Use more number of LSTM hidden layer or dropout to see if you develop a better model
# Extend the model to use pretrained word2vec or glove embeddings